craft_site/craft_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

craft_site/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("<int:id>", views.index, name="index"),
    path("v1/", views.v1, name="view 1"),
    path("", views.home, name="home"),
    path("create/", views.create, name="create"),
]

craft_site/main/models.py
from django.db import models
#python manage.py makemigrations та python manage.py migrate

# Create your models here.
class Booking(models.Model):
    name = models.CharField(max_length=200)
    trip_from = models.CharField(max_length=200)
    trip_to = models.CharField(max_length=200)
    day = models.CharField(max_length=200)
    data = models.DateField(verbose_name="data of trip")
    phone = models.IntegerField(default=0, null=False, blank=False, verbose_name='Client phone number')
    count_of_passengers = models.IntegerField(default=0, null=False, blank=False, verbose_name='Count of passengers')
    desc = models.CharField(max_length=200, default=0, null=True)
    registration_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name, self.trip_from, self.trip_to, self.day, self.data, self.phone, self.count_of_passengers, self.desc


class Routes(models.Model):
    cities_list = models.CharField(max_length=200)
    price = models.IntegerField(default=0, null=False, blank=False)
    day_start = models.CharField(max_length=200)
    day_finish = models.CharField(max_length=200)
    time_start = models.CharField(max_length=200)
    registration_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cities_list, self.price, self.day_start, self.day_finish, self.time_start


class Cars(models.Model):
    name = models.CharField(max_length=200)
    year = models.IntegerField(default=0, null=False, blank=False)
    photos = models.ImageField(upload_to='car_photos/')
    information = models.CharField(max_length=200)
    registration_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name, self.year, self.information


class Driver(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField(default=0, null=False, blank=False)
    photo = models.ImageField(upload_to='driver_photos/')
    registration_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name, self.age


class Response(models.Model):
    name = models.CharField(max_length=200)
    response = models.CharField(max_length=200)
    registration_time = models.DateTimeField(auto_now_add=True)


class ToDoList(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

craft_site/main/forms.py
from django import forms


class CreateNewList(forms.Form):
    name = forms.CharField(label="Name", max_length=200)
    check = forms.BooleanField(required=False)


class AddNewBooking(forms.Form):
    name = forms.CharField(label="Name", max_length=200)
    trip_from = forms.CharField(label="City where trip start", max_length=200)
    trip_to = forms.CharField(label="City where trip finish", max_length=200)
    day = forms.CharField(label="Vivtorok, chetver, patnutsa, nedila", max_length=200)
    data = forms.DateField(label="data of trip")
    phone = forms.IntegerField(label="mobile phone")
    count_of_passengers = forms.IntegerField(label="count of passengers")
    desc = forms.CharField(label="desc of trip")

craft_site/main/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import ToDoList, Booking
from .forms import CreateNewList, AddNewBooking

def index(response, id):
    ls = ToDoList.objects.get(id=id)
    return render(response, "main/list.html", {"ls":ls})

def v1(response):
    return HttpResponse("<h1>view 1</h1>")

def home(response):
    return render(response, "main/home.html", {})

def create(response):
    if response.method == "POST":
        form = CreateNewList(response.POST)

        if form.is_valid():
            n = form.cleaned_data["name"]
            t = ToDoList(name=n)
            t.save()

        return HttpResponseRedirect("/%i" % t.id)

    else:
        form = CreateNewList()

    return render(response, "main/create.html", {"form": form})

craft_site/main/templates/main/base.html
<html>
<head>
    <title>{% block title %}Test Site{% endblock %}</title>
</head>

<body>
    <div id="content" name="content">
	{% block content %}
	{% endblock %}
    </div>

</body>
</html>

craft_site/main/templates/main/create.html
{% extends 'main/base.html' %}
{% block title %}
Create New List
{% endblock %}

{% block content %}
	<h3>Create a New To Do List</h3>
	<br>
	<form method="post" action="/create/" class="form-group">
		{% csrf_token %}
		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
	  		<button name="save" type="submit" class="btn btn-success">Create</button>
	  		</div>
	  		{{form.name}}
		</div>
	</form>
{% endblock %}

craft_site/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h1>Home Page</h1>
{% endblock %}

craft_site/main/templates/main/list.html
{% extends "main/base.html" %}
{% block title %}View List{% endblock %}

{% block content %}
    <h1>{{ls.name}}</h1>
    <form method="post" action="#">
    {% csrf_token %}
        <ul>
            {% for item in ls.item_set.all %}
                {% if item.complete == True %}
                    <li><input type="checkbox", value="clicked", name="c{{item.id}}" checked>{{item.text}}</li>
                {% else %}
                    <li><input type="checkbox", value="clicked", name="c{{item.id}}">{{item.text}}</li>
                {% endif %}
            {% endfor %}
        </ul>
        <button type="submit", name="newItem", value="newItem">Add Item</button>
        <input type="text", name="new">
        <button type="submit", name="save", value="save">Save</button>
    </form>
{% endblock %}